### ISSUE TITLE
YAML Error on rbac.yaml caused by wrong indentation

### ISSUE THREAD

**Issue by JulianJessen** [snowdrop/godaddy-webhook#14]
https://github.com/snowdrop/godaddy-webhook/blob/6bc57dff24aaa6c435db0aa3af2777d22e3409ac/deploy/helm/templates/rbac.yaml#L115

The line is indented too much (2 spaces plus 4 indentation = 6, needs 4).
`__{{ include "godaddy-webhook.labels" . | indent 4 }}`

Same with this line:
https://github.com/snowdrop/godaddy-webhook/blob/6bc57dff24aaa6c435db0aa3af2777d22e3409ac/deploy/helm/templates/rbac.yaml#L131

Please delete the leading two spaces to fix it.

**Comment by freme** [comment]
can confirm - please fix. thx.

**Comment by cmoulliard** [comment]
Fixed on main branch
