### ISSUE TITLE
Create CI/CD for helm chart deployment

### ISSUE THREAD

**Issue by PhotoTeeborChoka** [snowdrop/godaddy-webhook#18]
The helm chart can be installed without any issues, the problem arises when some CD tools (e.g. ArgoCD) need to deploy this helm, they need it properly packaged.

To solve this issue, it would be beneficial to have a [Github Action](https://github.com/stefanprodan/helm-gh-pages) to publish the packaged helm chart into the `gh-pages` branch that would be published on `github.io` as GitHub Page.

**Comment by cmoulliard** [comment]
Do you want to propose a PR ? @PhotoTeeborChoka
