### ISSUE TITLE
Godaddy API doesn't appear to be called

### ISSUE THREAD

**Issue by rsf123** [snowdrop/godaddy-webhook#2]
I've installed cert-manager and the godaddy-webhook. After following the directions in the README, I can see my certificate request getting created.  However, it doesn't appear that the GoDaddy API is ever called. 

Is there a way to check logs/status on the webhook to see if its getting the DNS challenge back from LetsEncrypt and making the call to the GoDaddy API?

**Comment by rbadillo** [comment]
Hey, did you get it working ?

**Comment by ilmircod** [comment]
I followed the instructions and got a wildcard certificate. It works )

**Comment by cmoulliard** [comment]
> I followed the instructions and got a wildcard certificate. It works )

So, is there or not an issue ? If no, I propose to close the ticket
