### ISSUE TITLE
Broken tags on the 0.4.0 release.

### ISSUE THREAD

**Issue by CompPhy** [snowdrop/godaddy-webhook#52]
First off... Thank you for your work here.

Not onto the problem... I'm getting this when trying to update to the 0.4.0 release:

```
4m (x4 over 5m23s)        Warning   Failed                          Pod/godaddy-webhook-5d66f54455-qm8vh            Failed to pull image "quay.io/snowdrop/cert-manager-webhook-godaddy:0.4.0": rpc error: code = NotFound desc = failed to pull and unpack image "quay.io/snowdrop/cert-manager-webhook-godaddy:0.4.0": failed to resolve reference "quay.io/snowdrop/cert-manager-webhook-godaddy:0.4.0": quay.io/snowdrop/cert-manager-webhook-godaddy:0.4.0: not found
```

In the quay.io repository, for sure there's no tag "0.4.0".  Although it does show that "latest" updated.

Looking into the GitHub workflow job... it looks like something got lost with the version numbers because this is what it pushed:

https://github.com/snowdrop/godaddy-webhook/actions/runs/11718585970/job/32640161023
```
 #27 exporting to image
#27 pushing layers 4.9s done
#27 pushing manifest for quay.io/snowdrop/cert-manager-webhook-godaddy:main-f12e6fb@sha256:52a8defe1e0c00b5da239c70aee3ccd2fd1968c24ae040c1385dcd92f1fcf839
#27 pushing manifest for quay.io/snowdrop/cert-manager-webhook-godaddy:main-f12e6fb@sha256:52a8defe1e0c00b5da239c70aee3ccd2fd1968c24ae040c1385dcd92f1fcf839 3.7s done
#27 pushing layers 0.5s done
#27 pushing manifest for quay.io/snowdrop/cert-manager-webhook-godaddy:latest@sha256:52a8defe1e0c00b5da239c70aee3ccd2fd1968c24ae040c1385dcd92f1fcf839
#27 pushing manifest for quay.io/snowdrop/cert-manager-webhook-godaddy:latest@sha256:52a8defe1e0c00b5da239c70aee3ccd2fd1968c24ae040c1385dcd92f1fcf839 0.9s done
#27 DONE 12.5s
```

**Comment by cmoulliard** [comment]
I will tag the image and push it on the quay repository as I dont think that the current github workflow when we release do it.

**Comment by cmoulliard** [comment]
Image:latest has been tagged as `0.4.0`
![Screenshot 2024-11-12 at 10 27 04](https://github.com/user-attachments/assets/d256b0bb-c63f-428e-ae0f-317be243bc38)

**Comment by cmoulliard** [comment]
Can you check and close the ticket if fixed ? @CompPhy

**Comment by CompPhy** [comment]
I guess I was hoping that opening this issue would to a fix in the automation.  Seems kind of suspect that you have to manually do this every time, there's lots of other projects that have this figured out and new versions are just "automatic" based on the chart/app version numbers.  The workflow tools have the ability to parse the version number directly from your config files and tag things automatically.

Either way, I guess this is good enough for now.  Will have a look at it once my other issue is addressed: #53

**Comment by cmoulliard** [comment]
This project has been created historically to support our needs at red hat part of the team maintaining spring boot projects and was not intended to be released. As I'm alone on this project and working on many others, I cannot handle everything and contribution are more than welcome

**Comment by cmoulliard** [comment]
I will review the existing job as the image is not pushed/tagged anymore as commented: https://github.com/snowdrop/godaddy-webhook/blob/main/.github/workflows/release.yml#L55-L69

**Comment by cmoulliard** [comment]
Fixed. 
![Screenshot 2024-11-13 at 16 24 18](https://github.com/user-attachments/assets/f06c30e6-c178-4918-962c-679026ea677d)
